### ISSUE TITLE
Touch ID cannot be used when valet.sh asks for sudo password

### ISSUE THREAD

**Issue by sippsolutions** [valet-sh/valet-sh#10]
With https://www.imore.com/how-use-sudo-your-mac-touch-id you can use your touch ID for sudo actions.
Unfortunately when using for example `valet.sh install` the user still gets asked for the password instead of using touch ID.

Expected behavior / change request: Touch ID can be used for valet.sh sudo actions.

**Comment by sippsolutions** [comment]
FYI: To configure Touch ID for sudo, follow [these steps](https://apple.stackexchange.com/a/306324).
You can then enter a random string for the password prompt and will be asked for your Touch ID afterwards.

**Comment by dittertp** [comment]
Fixed in milestone rc1
