### ISSUE TITLE
Touch ID is not available for init-instance

### ISSUE THREAD

**Issue by sippsolutions** [valet-sh/valet-sh#102]
When I enter `valet.sh init-instance` or `valet.sh restore` I cannot use Touch ID as identification, I have to type the password manually.

**Comment by dittertp** [comment]
the "init-instance" and "restore" command can take a couple of minutes. When we use the "native" sudo priviliege escalation the chance is very high that the commands will fail, because the cache time time for sudo permission run out. Thats the reason we can not use it for the "install" as well.

**Comment by sippsolutions** [comment]
We do not plan to change this behavior at the moment.
