### ISSUE TITLE
valet.sh enable should start the service as well

### ISSUE THREAD

**Issue by sippsolutions** [valet-sh/valet-sh#104]
`valet.sh service enable mysql80` should also trigger a
`valet.sh service start mysql80`

**Comment by dittertp** [comment]
thats already the case, or at least it should be. mysql8 could take a couple of seconds to start, maybe you have not waited long enough?

**Comment by sippsolutions** [comment]
*Testing*
- [x] Ubuntu 20.04
- [x] macOS 10.15.7
