### ISSUE TITLE
valet secure command

### ISSUE THREAD

**Issue by alexander-kaftan-techdivision** [valet-sh/valet-sh#15]
Future (command does not exist yet):
The valet secure command should use some better hashing algorithm than sha1 and maybe >= 4096 bits for its test certificate.
The reason: you cannot import sha1 cert chains in firefox (or will not be able to do so in a not so far future)

**Comment by alexander-kaftan-techdivision** [comment]
maybe an auto import in chrome and firefox would be also nice

**Comment by zelgerj** [comment]
hey @alexander-kaftan-techdivision thanks for you feedback. It's planed to do so in the first beta version of valet-sh.

**Comment by dittertp** [comment]
Fixed in 2.x branch
