### ISSUE TITLE
invald value for sys_temp_dir php variable in homebrew packages

### ISSUE THREAD

**Issue by dittertp** [valet-sh/valet-sh#188]
It seems that the sys_temp_dir variable has an invalid value on macos (homebrew packages) and therefore uploads to the temp directory do not work properly

**Comment by dittertp** [comment]
I can't reproduce the problem at the moment.

**Comment by sippsolutions** [comment]
issue is reproducible, could be fixed by setting the fastcgi_param PHP_VALUE of `sys_temp_dir=/private/var/tmp`

**Comment by sippsolutions** [comment]
$ php -r 'echo sys_get_temp_dir();' 
	/private/var/tmp
