### ISSUE TITLE
Support for OpenSearch2

### ISSUE THREAD

**Issue by mdecamposmendes** [valet-sh/valet-sh#232]
OpenSearch2 got released on the 26th of may 2022. [Blog-Post](https://opensearch.org/blog/releases/2022/05/opensearch-2-0-is-now-available/)
Since there is already an opensearch role, it would be nice to also have an opensearch2 role.

**Comment by sippsolutions** [comment]
Testing: 

$ curl 127.0.0.1:9222                       
{
  "name" : "00741-mbp",
  "cluster_name" : "opensearch2",
  "cluster_uuid" : "ay8kVnkqRpWUEA8kewXqUA",
  "version" : {
    "distribution" : "opensearch",
    "number" : "2.4.1",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2022-12-03T01:36:25Z",
    "build_snapshot" : false,
    "lucene_version" : "9.4.2",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
