### ISSUE TITLE
Path for PHP Binary is missing in PATH variable

### ISSUE THREAD

**Issue by sippsolutions** [valet-sh/valet-sh#242]
When running code within magento and using exec() with for example `/usr/bin/env php random_binary` the command fails with `env: php: No such file or directory`.
Adding `export PATH=/usr/local/bin:$PATH;` in front of the command fixes the problem. `/usr/local/bin` should be added to the PATH variable by default.

**Comment by dittertp** [comment]
fixed in https://github.com/valet-sh/valet-sh/commit/a77f175fc8e95e7dc00bb6196ad7f6ac449216bf
