### ISSUE TITLE
Question / Request: can "valet.sh installed shell" be optional ?

### ISSUE THREAD

**Issue by yavery** [valet-sh/valet-sh#275]
Context: after installing valet.sh, I notice my original shell is being replaced by valet.sh shell. Here are some observations:
- typing anything in the new shell feels slower, "hesitating"  (on a m2-max)
- switching back to my normal bash profile, terminal feel normal again, all the commands of valet.sh still working just fine

Questions
1. is there any functional reason to use the **valet.sh installed shell** ?
2. is there a command to add AND remove the **valet.sh installed shell** ?  ~ some people may prefer to use the default or their own terminal customization
3. is there a way to manually incorporate part of **valet.sh installed shell** ?  ~ some people may prefer to incorporate just some aspects

**Comment by dittertp** [comment]
Hello @yeyu-avery ,

MacOS uses zsh as shell by default, so this is also the default value in valet.sh.

You can switch back to "bash" at any time (documentation https://valet.sh/commands/config/). There are no functional disadvantages or incompatibilities.

1. No
2. No, the shell installation cannot be skipped, but you can switch to "bash" via the configuration linked above.
3. At the moment, only the default shell can be changed. Do you have an example of what you would like to change?


Philipp

**Comment by yavery** [comment]
@dittertp 

Appreciate your replies!

"RE: valet.sh is zsh as well" ~  but valet.sh is pretty opinionated with its style choices. I would suggest bringing on the shell customization should be at least optional. The current situation is similar to installing an IDE but notice it changes my OS theme.

However, the biggest problem I see is the slowness:
- when starting a new terminal tab, it takes a few seconds to be ready
- typing anything feels obvious latency as well

Do you also experience the slowness, any way to mitigate this ? 

Regards

**Comment by dittertp** [comment]
Hi @yavery 

ok, so you still use zsh? Your description of the behaviour fits the zsh extension "oh-my-zsh". This is actually hardcoded at the moment and would also be installed/activated again after each "valet.sh install". You can temporarily deactivate the extension in the .zshrc file. Comment or delete the following line:

`source $ZSH/oh-my-zsh.sh`

I am creating a ticket to make the installation optional.


Philipp

**Comment by yavery** [comment]
@dittertp 

Thank you for the information, that really helps.

It would be greatly appreciated if the custom shell is a choice at the installation.

Just out of curiosity, do you experience the similar slow terminal under valet.sh ?

**Comment by dittertp** [comment]
@yavery yes, as soon as the folder is a git repository, the extension executes some git commands, that's why there are the delays when starting it

**Comment by yavery** [comment]
@dittertp 

Thank you for the clarification! Great info helping me understanding why the delay.
