### ISSUE TITLE
A command to stub the .valet-sh.yml

### ISSUE THREAD

**Issue by zelgerj** [valet-sh/valet-sh#47]

**Comment by dittertp** [comment]
do you have a suggestion for a suitable command?

otherwise i would implement "valet.sh stub config" as command.

**Comment by zelgerj** [comment]
There are 2 options in my opinion:

1. `valet.sh init` similar to `composer init`

2. `valet.sh config init`

**Comment by dittertp** [comment]
I like `valet.sh init` the most, but can be missleading as there is also a "valet.sh init-instance" command. I still prefer option 1

**Comment by sippsolutions** [comment]
*Testing*
- [x] Ubuntu 20.04
- [x] macOS 10.15.7
