### ISSUE TITLE
Provide help parameter for all commands

### ISSUE THREAD

**Issue by sippsolutions** [valet-sh/valet-sh#57]
In order to understand what I have to type for a specific command to work, I need a -h parameter to show me what options I have.

* -h is available for all valet.sh commands
* every available parameter is described
* example usages are listed
* The help output should also be present in the documentation

If the -h output would be too long, maybe a link to the documentation page is ok.

**Comment by dittertp** [comment]
Fixed in https://github.com/valet-sh/valet-sh/commit/1ee6098edbc7b6f7537fec86312bf0e21d009229
