### ISSUE TITLE
Provide a mapping for PHP etc. equivalents

### ISSUE THREAD

**Issue by sippsolutions** [valet-sh/valet-sh#59]
It sometimes may be hard for users to remember which format of a PHP-Version the current command needs.
It would be good if I can type whatever of these combinations and a mapping will ensure the right task is executed:

How it is currently:
* php7.3 $(which composer) update
* valet.sh service restart php7.3
* valet.sh xdebug on 7.3
* valet.sh link myproject php73

How it should be:
* valet.sh service restart php73
* valet.sh service restart php7.3
* valet.sh service restart PHP73
* valet.sh service restart PHP7.3
* valet.sh xdebug on 7.3
* valet.sh xdebug on PHP7.3
* valet.sh xdebug on php73

**Comment by Mardl** [comment]
Basically I think that the service name in `valet.sh service list` could be the hook. This way I always have a reference point for what I want to start, debug or update. 
Currently the service name for php is for example `php73`.
