### ISSUE TITLE
install.sh crashes in pip-install step

### ISSUE THREAD

**Issue by sippsolutions** [valet-sh/valet-sh#61]
The install.sh seems to exit at installing pip sometimes:

```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/valet-sh/install/master/install.sh)"
Check Command Line Tools
Installing pip
```

When executing the command again, it seems to work.

**Comment by sippsolutions** [comment]
Idea: execute installer commands in a container

**Comment by zelgerj** [comment]
not reproducible

**Comment by zelgerj** [comment]
see https://github.com/valet-sh/valet-sh/issues/69
