### ISSUE TITLE
The process has been signaled with signal "9"

### ISSUE THREAD

**Issue by sippsolutions** [valet-sh/valet-sh#62]
With 7.3.24 the process sometimes crashes with signal 9 in FPM. A `valet.sh service restart php73` fixes the issue.

**Comment by dittertp** [comment]
the opcache second level caching on fs is now disabled

**Comment by sippsolutions** [comment]
The issue currently is not reproducible anymore. I will close this ticket for now.

**Comment by sippsolutions** [comment]
FYI: Issue is reproducible today (but only for my setup), a ` valet.sh service restart php73` temporarily fixes it.
Please feel free to follow up if it happens to you as well.

**Comment by sippsolutions** [comment]
FYI: it seems that when updating brew packages and the php binary gets upgraded, the service should be restarted (with the command stated above) to load the right binary.
