### ISSUE TITLE
Allow specification for mySQL version in db commands

### ISSUE THREAD

**Issue by sippsolutions** [valet-sh/valet-sh#63]
As a user of mySQL 8 I want to be able to specify the mySQL version when executing commands like `valet.sh db import`

**Comment by dittertp** [comment]
Hi, do you have an idea what the new command might look like?

Example:
   current command: valet.sh db import dump.sq.gz mydb
   possible new command variants: 
         valet.sh db import dump.sq.gz mydb mysql80
         valet.sh db import dump.sq.gz mydb --mysql80
         valet.sh db mysql80 import dump.sq.gz mydb
         valet.sh db-mysql80 import dump.sq.gz mydb

personally i don't like any of the possible variations. Do you have a better idea?

**Comment by sippsolutions** [comment]
Maybe it's enough to define the mySQL version the .valet-sh.yml file, see also #47
