### ISSUE TITLE
Install process on MacOS is unstable due to python version mismatch

### ISSUE THREAD

**Issue by dittertp** [valet-sh/valet-sh#68]
the install process should rely on a specific python3 version and use a private venv for valet-sh to avoid environment specific problems with python2, pip provided by MacOS itself or homebrew

**Comment by dittertp** [comment]
possible worflow for install routine:

MacOS:

	check whether homebrew is installed and if not it aborts the installation with an error (so homebrew must be installed beforehand)
	install brew package "python@3.9" - the package does NOT have to be linked, installation is sufficient
	create venv in valet-sh workdirectory: /usr/local/opt/python@3.9/bin/python3 -m venv /usr/local/valet-sh/venv
	Install python requirements via venv pip: /usr/local/valet-sh/venv/bin/pip3 install -q -r /usr/local/valet-sh/valet-sh/requirements.txt

	ansible-binary: /usr/local/valet-sh/venv/bin/ansible-playbook

Ubuntu:	

	install apt package "python3"
	create venv in valet-sh workdirectory: /usr/bin/python3 -m venv /usr/local/valet-sh/venv
	Install python requirements via venv pip: /usr/local/valet-sh/venv/bin/pip3 install -q -r /usr/local/valet-sh/valet-sh/requirements.txt

	ansible-binary: /usr/local/valet-sh/venv/bin/ansible-playbook


HINT: it may be useful to install the pip packages "setuptools" and "wheel" before installeing the valet-sh requirements!

**Comment by zelgerj** [comment]
fixed by https://github.com/valet-sh/valet-sh/commit/796cfcb525556188ccd3cb8f56a3f2e896102134
