### ISSUE TITLE
Add valet.sh phpstorm command

### ISSUE THREAD

**Issue by sippsolutions** [valet-sh/valet-sh#88]
We should implement the command `valet.sh phpstorm` (which simply triggers an `open -a PhpStorm .` in the current working directory on macOS) as it has been implemented in [valet+](https://github.com/techdivision/valet-plus/blob/master/cli/valet.php#L834) and some users might miss this feature

**Comment by dittertp** [comment]
There is no (real) equivalent for "open" on linux (Ubuntu). 

Blocked by #43

**Comment by sippsolutions** [comment]
*Testing*
- [ ] Ubuntu 20.04: phpstorm command does not exist (phpstorm installed via jetbrains toolbox)
- [x] macOS 10.15.7
