### ISSUE TITLE
Complete project instantiation via .valet-sh.yml

### ISSUE THREAD

**Issue by sippsolutions** [valet-sh/valet-sh#98]
As a developer I want to completely set up a project environment via `.valet-sh.yml` and `valet.sh init-instance`.

This command should enable/start/set the correct project environment versions for:
- php
- es
- mysql
- rabbitmq

If `init-instance` only starts the services but does not enable them for autostart, there should be another command to start the services again, otherwise the user will have to execute `valet.sh init-instance` again after rebooting or start all services manually if they are not enabled for autostart already.

It should also be possible to define commands to set up the project as defined with for example:
- composer install in ./
- composer install in ./src
- nvm install/use
- npm install in ./
- valet.sh link (with the correct project definer and php version)
- a database/media dump
  - with a parameter to define if the dump should be overwritten, checked if there is a new dump [shasum?], or maybe automatically checking of there already is a database present (when given a specific parameter), or do not import dump at all) into the correct mysql version (even if is it not the default one)
- other commands such as bin/magento s:up or basic bash commands (rabbitmqctl, gulp, phinx, ...)
- grumphp git:init - but this can also be added as a post-install script in ./composer.json
- create dev admin user for magento2 (bin/magento admin:user:create)
- SQL commands like `UPDATE cms_block/cms_page/core_config_data REPLACE(value, test-server.de, local.test)`

We should implement the possibility to define pre and post commands to cleanup (to ensure the command will succeed under any circumstances), such as:
- rm -rf vendor
- rm -rf tmp
- etc.
This will ensure that every init-instance will work the same and no temporary files etc. will change the behavior.

Other behavior:
- The command should fail if no `.valet-sh.yml` is present, with the notice that it's possible to generate one via `valet.sh init`.
- The command should fail if any sub-command fails to execute and display the error message.

See also #74, #47, #105, #106

**Comment by sippsolutions** [comment]
Missing functionality at the moment:

- [ ] Start the services (currently services are only being enabled, but if they are stopped manually they won't get started, see also #134)
- [ ] Creation of Magento2 admin user
- [x] Possibility to define scripts/db queries that will be executed post-install (this could be done via composer post_install scripts if we execute composer install in the project dir at the VERY end if the init-instance process, after the DB has been initialized etc.)
- [x] Possibility to skip the database sync (dropping/downloading/importing)
- [ ] The command should fail if no `.valet-sh.yml` is present, with the notice that it's possible to generate one via `valet.sh init`
- [ ] The command should fail if any sub-command fails to execute and display the error message
- [ ] Documentation for the .valet-sh.yml and for the init-instance and restore commands

**Comment by sydekumf** [comment]
Further features/ideas:
[] Magento instance should be installable via `setup:install` as an alternative to using a database dump
[] Magento instance should be set to `developer` mode at the end of the script (if not already)
[] At the end of the script Pacemaker should import files which can be configured by path
[] There should be a configurable list of setting configurations only for local development
```shell
    $PHP bin/magento deploy:mode:set developer &&
    $PHP bin/magento config:set 'admin/startup/menu_item_id' 'Magento_Config::system_config' &&
    $PHP bin/magento config:set 'admin/security/session_lifetime' 31536000 &&
    $PHP bin/magento config:set 'system/full_page_cache/caching_application' 1 &&
    $PHP bin/magento config:set 'admin/usage/enabled' 0 &&
    $PHP bin/magento config:set 'paypal/wpp/sandbox_flag' 1 &&
    $PHP bin/magento config:set 'twofactorauth/general/enable' 0 &&
    $PHP bin/magento config:set 'admin/security/admin_account_sharing' 1 &&
    $PHP bin/magento config:set 'dev/css/minify_files' 0 &&
    $PHP bin/magento config:set 'dev/js/minify_files' 0 &&
    $PHP bin/magento config:set 'dev/js/merge_files' 0 &&
    $PHP bin/magento config:set 'dev/js/enable_js_bundling' 0 &&
    $PHP bin/magento config:set 'dev/css/merge_css_files' 0
```

For the last two points as they are very specific: Maybe just add a generic section at the end of the script where additional bash commands can be executed to keep it more general.
